import { 
    TABLE_USERS, 
    STATIC_REFERENCE_TABLES, 
    ADMIN_REFERENCE_TABLES, 
    USER_REFERENCE_TABLES, 
    USER_REFERENCE_FEDERATIONS, 
    COMPETITION_TABLES, 
    COMPETITION_SESSION_TABLES, 
    COMPETITION_GROUP_TABLES, 
    CREATED_BY_USER_TABLES, 
    COMPETITION_RUNTIME_TABLES, 
    ORGANIZATION_RESULT_TABLES, 
} from './sync/config.js';

import { CREATE_COMPETITION_SQL } from './queries/competitions/create.js';
import { UPDATE_COMPETITION_SQL } from './queries/competitions/update.js';
import { DELETE_COMPETITION_SQL } from './queries/competitions/delete.js';

export { 
    TABLE_USERS, 
    STATIC_REFERENCE_TABLES,
    ADMIN_REFERENCE_TABLES,  
    USER_REFERENCE_TABLES, 
    USER_REFERENCE_FEDERATIONS, 
    COMPETITION_TABLES, 
    COMPETITION_SESSION_TABLES, 
    COMPETITION_GROUP_TABLES, 
    CREATED_BY_USER_TABLES, 
    COMPETITION_RUNTIME_TABLES, 
    ORGANIZATION_RESULT_TABLES, 
};

export const SYNC_OPERATIONS = {

  CREATE_COMPETITION: CREATE_COMPETITION_SQL,
  UPDATE_COMPETITION: UPDATE_COMPETITION_SQL,
  DELETE_COMPETITION: DELETE_COMPETITION_SQL,

} as const;