import { 
    STATIC_REFERENCE_TABLES, 
    REFERENCE_TABLES, 
    USER_REFERENCE_TABLES, 
    USER_REFERENCE_FEDERATIONS, 
    COMPETITION_TABLES, 
    SESSION_TABLES, 
    GROUP_TABLES, 
    TABLE_USERS, 
    USER_TABLES, 
} from './sync.config.js';

export { 
    STATIC_REFERENCE_TABLES,
    REFERENCE_TABLES,  
    USER_REFERENCE_TABLES, 
    USER_REFERENCE_FEDERATIONS, 
    COMPETITION_TABLES, 
    SESSION_TABLES, 
    GROUP_TABLES, 
    TABLE_USERS, 
    USER_TABLES, 
};