import { 
    STATIC_REFERENCE_TABLES, 
    USER_REFERENCE_TABLES, 
    USER_REFERENCE_FEDERATIONS,
    USER_TABLES, 
} from './sync.config.js';

export { 
    STATIC_REFERENCE_TABLES, 
    USER_REFERENCE_TABLES, 
    USER_REFERENCE_FEDERATIONS, 
    USER_TABLES, 
};